
CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);


CREATE TABLE Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    author varchar(200) NOT NULL,
    name varchar(200) NOT NULL,
    year_of_production int
);


INSERT INTO Person(name, year_of_birth)
VALUES
('Иванов Иван Иванович', 1970),
('Петров Петр Петрович', 1960),
('Алексеев Алексей Алексеевич', 1989);