
CREATE TABLE Person(
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_birth int
);


CREATE TABLE Book(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES person(id),
    author varchar(200) NOT NULL,
    name varchar(200) NOT NULL,
    year_of_production int
);


INSERT INTO Person(name, yearofbirth) VALUES ('Иванов Иван Иванович', 1970);
INSERT INTO Person(name, yearofbirth) VALUES ('Петров Петр Петрович', 1960);
INSERT INTO Person(name, yearofbirth) VALUES ('Алексеев Алексей Алексеевич', 1989);