
CREATE TABLE Person(
    id int  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) NOT NULL,
    year_of_birth int NOT NULL,
    password varchar NOT NULL
);

select * from Person;

INSERT INTO Person(username, year_of_birth, password)
VALUES
    ('IvanovII', 1970, 'test_password'),
    ('PetrovPP', 1960, 'test_password'),
    ('LazarevLL', 1989, 'test_password'),
    ('SidorovSS', 1975, 'test_password');


CREATE TABLE Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year_of_production int,
    date_of_rent TIMESTAMP
);




INSERT INTO Book(name, author, year_of_production)
VALUES
('Омон Ра', 'Пелевин Виктор', 1991),
('Чапаев и Пустота', 'Пелевин Виктор', 1996),
('Священная книга оборотня', 'Пелевин Виктор', 2004),
('Зелёная миля', 'Стивен Кинг', 2004),
('Сияние', 'Стивен Кинг', 1977),
('Противостояние', 'Стивен Кинг', 1978),
('Воскресение', 'Лев Толстой', 1899),
('Детство', 'Лев Толстой', 1852),
('Отрочество', 'Лев Толстой', 1854),
('Юность', 'Лев Толстой', 1857);

select * from Person;
select * from Book;

select * from Book
join Person P on Book.person_id = P.id;

drop table Person;
drop table Book;