CREATE TABLE Actor
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    age  int check (age > 10 and age < 120)
);

CREATE TABLE Movie
(
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               varchar(100) NOT NULL,
    year_of_production int check (year_of_production > 1900)
);

CREATE TABLE Actor_Movie
(
    actor_id int references Actor (id),
    movie_id int references Movie (id),
    PRIMARY KEY (actor_id, movie_id)
);







