
CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);


CREATE TABLE Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year_of_production int,
    date_of_rent TIMESTAMP
);


INSERT INTO Person(name, year_of_birth)
VALUES
('Иванов Иван Иванович', 1970),
('Петров Петр Петрович', 1960),
('Алексеев Алексей Алексеевич', 1989),
('Лазарев Лазарь Лазаревич', 1995),
('Сидоров Сидр Сидорович', 1975);

INSERT INTO Book(name, author, year_of_production)
VALUES
('Омон Ра', 'Пелевин Виктор', 1991),
('Чапаев и Пустота', 'Пелевин Виктор', 1996),
('Священная книга оборотня', 'Пелевин Виктор', 2004),
('Зелёная миля', 'Стивен Кинг', 2004),
('Сияние', 'Стивен Кинг', 1977),
('Противостояние', 'Стивен Кинг', 1978),
('Воскресение', 'Лев Толстой', 1899),
('Детство', 'Лев Толстой', 1852),
('Отрочество', 'Лев Толстой', 1854),
('Юность', 'Лев Толстой', 1857);

select * from Person;

select * from Book
join Person P on Book.person_id = P.id;

drop table Person;
drop table Book;